--BUSCANDO POR NOME E ANO 
SELECT Nome, Ano FROM Filmes

--BUSCANDO POR NOME E ANO (CRESCENTE)
SELECT * FROM Filmes ORDER BY Ano ASC

--BUSCANDO FILME 'De Volta para o Futuro' COM NOME, ANO E DURAÇÃO
SELECT * FROM Filmes WHERE Nome = 'De Volta para o Futuro'

--BUSCANDO FILMES DO ANO 1997
SELECT * FROM Filmes WHERE Ano = 1997

--BUSCANDO FILMES APÓS O ANO 2000
SELECT * FROM Filmes WHERE Ano > 2000

--BUSCANDO FILMES COM DURAÇÃO MAIOR QUE 100 E MENOR QUE 150 (CRESCENTE)
SELECT * FROM Filmes WHERE Duracao > 100 AND Duracao < 150 ORDER BY Duracao ASC

--BUCANDO A QUANTIDADE DE FILMES EM CADA ANO ORDENADO PELA DURANÇÃO (DECRESCENTE)
SELECT Ano, COUNT(*) Quantidade FROM Filmes GROUP BY (Ano) ORDER BY Quantidade DESC

--BUSCANDO ATORES MASCULINOS (NOME E SOBRENOME)
SELECT * FROM Atores WHERE Genero = 'M'

--BUSCANDO ATORES MASCULINOS (NOME E SOBRENOME) ORDENANDO PELO NOME
SELECT * FROM Atores WHERE Genero = 'F' ORDER BY PrimeiroNome

--BUSCANDO O NOME DO FILME E O GÊNERO
SELECT Nome, Genero FROM FilmesGenero
INNER JOIN Filmes ON Filmes.Id = FilmesGenero.IdFilme
INNER JOIN Generos ON Generos.Id = FilmesGenero.IdGenero

--BUSCANDO FILMES DO GÊNERO MISTÉRIO
SELECT Nome, Genero FROM FilmesGenero
INNER JOIN Filmes ON Filmes.Id = FilmesGenero.IdFilme
INNER JOIN Generos ON Generos.Id = FilmesGenero.IdGenero
WHERE Genero = 'Mistério'

--BUSCANDO FILME + ATORES (NOME, SOBRENOME) E O PAPEL
SELECT Nome, PrimeiroNome, UltimoNome, Papel FROM ElencoFilme
INNER JOIN Filmes ON Filmes.Id = ElencoFilme.IdFilme
INNER JOIN Atores ON Atores.Id = ElencoFilme.IdAtor





